apiVersion: v1
kind: Service
metadata:
  name: mechtron-docs
  labels:
    {{- include "docs.labels" . | nindent 4 }}
spec:
  type: ClusterIp 
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "docs.selectorLabels" . | nindent 4 }}
