[package]
name = "mechtron"
version = "0.2.0-rc1"
authors = ["Scott Williams <scott@mightydevco.com>"]
edition = "2021"
homepage = "http://starlane.io"
repository = "https://github.com/mechtronium/starlane"
license = "MIT"
description = "The Wasm Package to help easily create a Mechtron"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
mechtron-common = "0.2.0-rc1"
lazy_static = "1.4.0"
wasm_membrane_guest = "0.2.0"
mesh-portal = "0.2.0-rc1"
bincode = "1.3.3"

serde_json = "1.0.61"
serde = { version="1.0.69", features=['derive','rc'] }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
#wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]

[profile.release]
# Tell `rustc` to optimize for small code size.
#opt-level = "s"
